name: directory-service actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set Settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "github", "url": "https://maven.pkg.github.com/bcollins92/artefacts"}]'
        servers: '[{ "id": "github", "username": "bcollins", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
        profiles: '[{ "id": "sonar", "activation":{ "activeByDefault" : "true" }, "properties": {"sonar.host.url" : "https://sonarcloud.io" }}]'
      
    - name: Run tests with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.coverage.jacoco.xmlReportPaths="./target/site/jacoco"

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: bc92/directory-service:latest
        push: true